const {chromium,launchOptions}=require('./pw');
const assert=require('assert/strict');
const fs=require('fs');
const path=require('path');
const http=require('http');

(async()=>{
  const server=http.createServer((req,res)=>{
    const name=req.url.split('?')[0]==='/index.html' ? 'index.html' : 'singles.html';
    res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'}); res.end(fs.readFileSync(path.join(__dirname,name)));
  });
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  let browser; let checks=0;
  const check=(condition,message)=>{ assert(condition,message); checks++; };
  try {
    browser=await chromium.launch(launchOptions());
    const context=await browser.newContext({viewport:{width:375,height:812},deviceScaleFactor:2});
    const page=await context.newPage(), errors=[];
    page.on('pageerror',e=>errors.push(e.message)); page.on('dialog',d=>d.accept());
    const url=`http://127.0.0.1:${server.address().port}/singles.html`;
    await page.goto(url);
    await page.evaluate(()=>localStorage.setItem('badminton-court-session-v1','original-data'));
    check(await page.locator('#playerCount option').count()===11,'2〜12名');
    check(await page.locator('#courtCount option').count()===4,'1〜4コート');
    await page.selectOption('#playerCount','7'); check(await page.locator('#generateBtn').isDisabled(),'人数不足時は作成不可');
    await page.selectOption('#playerCount','12'); await page.click('#generateBtn');
    check(await page.locator('.round-card').count()===10,'10節生成');
    check(await page.locator('.court-match').count()===40,'4コート');
    check((await page.locator('.round-card').first().innerText()).includes('12番'),'初回休み12番');
    const before=await page.evaluate(()=>JSON.stringify(session));
    await page.reload(); check(await page.evaluate(()=>JSON.stringify(session))===before,'保存復元一致');
    check((await page.locator('#status').innerText()).includes('復元'),'復元通知');
    check(await page.evaluate(()=>localStorage.getItem('badminton-court-session-v1'))==='original-data','通常版の保存を保護');
    await page.selectOption('#mode','pairs'); await page.selectOption('#roundCount','30');
    await page.click('#generateBtn');
    check(await page.locator('.round-card').count()===30,'30節生成');
    check((await page.locator('.court-match').first().innerText()).includes('1番ペア'),'固定ペア表示');
    check((await page.locator('#infoBox').innerText()).includes('24名'),'ペア単位の説明');
    await page.locator('#setup details summary').click();
    await page.fill('#forcedRests','1: 12\n3: 9'); await page.click('#generateBtn');
    check((await page.locator('.round-card').first().locator('.rest').innerText()).includes('12番ペア*'),'指定休み表示');
    check(await page.evaluate(()=>session.rounds[2].rest.includes(9)),'指定休み反映');
    const valid=await page.evaluate(()=>JSON.stringify(session));
    await page.fill('#forcedRests','1: 1,2,3,4,5'); await page.click('#generateBtn');
    check(await page.evaluate(()=>JSON.stringify(session))===valid,'無効入力時に表を維持');
    check((await page.locator('#status').innerText()).includes('超え'),'休み枠エラー');
    await page.locator('#changePanel summary').click();
    await page.selectOption('#consumedRound','2'); await page.locator('#memberChips input[value="9"]').uncheck();
    await page.click('#changeBtn'); check(await page.evaluate(()=>JSON.stringify(session))===valid,'指定番号の離脱を拒否して表を維持');
    await page.locator('#memberChips input[value="9"]').check();
    await page.locator('#memberChips input[value="12"]').uncheck();
    await page.selectOption('#changeCourts','3'); await page.click('#changeBtn');
    const changed=await page.evaluate(()=>session);
    check(await page.inputValue('#consumedRound')==='2','completed round retained after edit');
    check(JSON.stringify(changed.rounds.slice(0,2))===JSON.stringify(JSON.parse(valid).rounds.slice(0,2)),'終了節を維持');
    check(changed.rounds.slice(2).every(r=>r.courts===3 && !r.players.includes(12)),'途中変更反映');
    check(await page.locator('.change-note').count()===1,'変更位置表示');
    await page.reload(); check(await page.evaluate(()=>JSON.stringify(session))===JSON.stringify(changed),'途中変更後の復元');
    check(await page.inputValue('#consumedRound')==='2','completed round retained after reload');
    await page.locator('#changePanel summary').click(); await page.selectOption('#consumedRound','29');
    await page.locator('#memberChips input[value="12"]').check(); await page.selectOption('#changeCourts','4'); await page.click('#changeBtn');
    check(await page.locator('.round-card').count()===30,'最終節変更で全節維持');
    check(await page.evaluate(()=>session.rounds[29].players.includes(12)),'復帰反映');
    check(await page.inputValue('#consumedRound')==='29','completed round retained after repeated edit');
    for(const width of [320,375,600]) {
      await page.setViewportSize({width,height:812});
      check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width}pxではみ出しなし`);
    }
    await page.setViewportSize({width:375,height:812});
    await page.evaluate(()=>{
      window.spoken=[];
      Object.defineProperty(window,'speechSynthesis',{value:{cancel(){},speak(u){window.spoken.push(u.text);}}});
    });
    await page.locator('.round-header button').first().click();
    check((await page.evaluate(()=>window.spoken[0])).includes('番ペア'),'ペア読み上げ');
    const canvas=await page.evaluate(()=>{const c=makeImage(20);return {w:c.width,h:c.height,data:c.toDataURL()};});
    check(canvas.w===800 && canvas.h<4000 && canvas.data.length>10000,'PNG生成');
    const downloadPromise=page.waitForEvent('download'); await page.getByRole('button',{name:'画像保存 21〜30節',exact:true}).click();
    const download=await downloadPromise; check(download.suggestedFilename()==='pairs-court-21-30.png','PNGダウンロード');
    const work=path.join(__dirname,'work','singles-preview'); fs.mkdirSync(work,{recursive:true});
    await download.saveAs(path.join(work,'pairs-court-21-30.png'));
    await page.evaluate(()=>window.scrollTo(0,0));
    await page.screenshot({path:path.join(work,'mobile.png'),fullPage:false});
    await page.locator('.round-card').first().screenshot({path:path.join(work,'round.png')});
    await page.locator('.stats').screenshot({path:path.join(work,'stats.png')});
    const hash=await page.evaluate(()=>SHARE_PREFIX+encodeShare(session));
    const stored=await page.evaluate(()=>localStorage.getItem(STORAGE_KEY));
    const viewer=await context.newPage(); viewer.on('pageerror',e=>errors.push(e.message));
    await viewer.goto(url+hash);
    check(await viewer.locator('#setup').isHidden(),'共有閲覧時は入力非表示');
    check(await viewer.locator('#changePanel').isHidden(),'共有閲覧時は変更不可');
    check(await viewer.locator('.round-card').count()===30,'共有復元');
    check(await viewer.evaluate(()=>localStorage.getItem(STORAGE_KEY))===stored,'共有で端末保存を上書きしない');
    await context.grantPermissions(['clipboard-read','clipboard-write']);
    await viewer.evaluate(()=>Object.defineProperty(navigator,'share',{value:undefined,configurable:true}));
    await viewer.getByRole('button',{name:'対戦表のリンクを共有'}).click();
    check((await viewer.evaluate(()=>navigator.clipboard.readText())).includes('#sp1='),'共有リンクをコピー');
    const otherContext=await browser.newContext(); const other=await otherContext.newPage();
    await other.goto(url+hash); check(await other.locator('.round-card').count()===30,'別端末相当で共有復元');
    check(await other.evaluate(()=>localStorage.getItem(STORAGE_KEY))===null,'別端末で共有を保存しない');
    await otherContext.close();
    await viewer.goto(url+'#sp1=broken');
    await viewer.waitForFunction(()=>document.getElementById('results').children.length===0 && document.getElementById('status').textContent.length>0);
    check(await viewer.locator('.round-card').count()===0,'破損共有を拒否');
    check(await viewer.locator('#setup').isHidden(),'破損共有でも元保存を表示しない');
    await page.getByRole('button',{name:'消去して最初から'}).click(); await page.reload();
    check(await page.locator('.round-card').count()===0,'消去後は復元されない');
    check(await page.evaluate(()=>localStorage.getItem('badminton-court-session-v1'))==='original-data','消去時も通常版を保護');
    await page.evaluate(()=>localStorage.setItem(STORAGE_KEY,'{"version":1}')); await page.reload();
    check((await page.locator('#status').innerText()).includes('復元できません'),'破損保存から復帰');
    await page.click('#generateBtn'); check(await page.locator('.round-card').count()===10,'破損保存後に新規生成');
    // Cancellation must preserve both the active table and its saved copy.
    const cancelBefore=await page.evaluate(()=>JSON.stringify(session));
    page.removeAllListeners('dialog'); page.on('dialog',d=>d.dismiss());
    await page.click('#generateBtn');
    check(await page.evaluate(()=>JSON.stringify(session))===cancelBefore,'cancel regeneration preserves table');
    await page.locator('#changePanel summary').click();
    await page.selectOption('#consumedRound','5'); await page.selectOption('#changeCourts','3'); await page.click('#changeBtn');
    check(await page.evaluate(()=>JSON.stringify(session))===cancelBefore,'cancel member edit preserves table');
    await page.getByRole('button',{name:'\u6d88\u53bb\u3057\u3066\u6700\u521d\u304b\u3089'}).click();
    check(await page.evaluate(()=>JSON.stringify(session))===cancelBefore,'cancel deletion preserves table');
    check(await page.evaluate(()=>localStorage.getItem(STORAGE_KEY))===cancelBefore,'cancellations preserve saved copy');
    page.removeAllListeners('dialog'); page.on('dialog',d=>d.accept());
    // Backward compatibility with the first version of this new page.
    await page.evaluate(data=>{const old=JSON.parse(data);delete old.completedThrough;localStorage.setItem(STORAGE_KEY,JSON.stringify(old));},stored);
    await page.reload();
    check(await page.locator('.round-card').count()===30,'legacy data restores');
    check(await page.inputValue('#consumedRound')==='29','legacy data selects latest member-change boundary');
    // Storage quota errors retain the generated result and report failed saving.
    const savedBeforeFailure=await page.evaluate(()=>localStorage.getItem(STORAGE_KEY));
    await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('full','QuotaExceededError');};});
    await page.click('#generateBtn');
    check(await page.locator('.round-card').count()===30,'quota error does not erase generated table');
    check(await page.evaluate(()=>document.getElementById('status').textContent.includes('\u4fdd\u5b58\u3067\u304d\u307e\u305b\u3093')),'quota error is reported');
    check(await page.evaluate(()=>localStorage.getItem(STORAGE_KEY))===savedBeforeFailure,'quota error preserves prior saved table');
    // Clipboard fallback and cancellation of the native share sheet.
    await page.evaluate(()=>{
      Object.defineProperty(navigator,'share',{value:undefined,configurable:true});
      Object.defineProperty(navigator,'clipboard',{value:undefined,configurable:true});
    });
    let fallbackURL=''; page.removeAllListeners('dialog');
    page.on('dialog',async d=>{if(d.type()==='prompt') fallbackURL=d.defaultValue();await d.dismiss();});
    await page.evaluate(()=>shareLink()); check(fallbackURL.includes('#sp1='),'clipboard unavailable falls back to copy dialog');
    await page.evaluate(()=>Object.defineProperty(navigator,'share',{value:()=>Promise.reject(new DOMException('cancel','AbortError')),configurable:true}));
    const shareStatus=await page.locator('#status').innerText();
    await page.evaluate(()=>shareLink());check(await page.locator('#status').innerText()===shareStatus,'share cancellation is handled');
    const blocked=await browser.newContext();
    await blocked.addInitScript(()=>{
      Storage.prototype.getItem=function(){throw new DOMException('blocked','SecurityError');};
      Storage.prototype.setItem=function(){throw new DOMException('blocked','SecurityError');};
    });
    const blockedPage=await blocked.newPage();blockedPage.on('pageerror',e=>errors.push(e.message));
    await blockedPage.goto(url);await blockedPage.click('#generateBtn');
    check(await blockedPage.locator('.round-card').count()===10,'blocked localStorage still permits table generation');
    await blocked.close();
    await page.goto(url.replace('singles.html','index.html')); check(await page.locator('a[href="singles.html"]').count()===1,'通常版からの入口');
    check(errors.length===0,'JavaScript例外なし: '+errors.join(','));
    console.log(`Singles browser: ${checks} checks passed. Preview: work/singles-preview/`);
  } finally { if(browser) await browser.close(); await new Promise(resolve=>server.close(resolve)); }
})().catch(e=>{console.error(e);process.exitCode=1;});
